### ISSUE TITLE
The /smelt and /smeltall commands are not working for raw mutton.

### ISSUE THREAD

**Issue by andrewkm** [therealspoljo/Smelter#1]
The /smelt and /smeltall commands are not working for raw mutton.
Hold raw mutton and do /smelt.

**Comment by therealspoljo** [comment]
Thanks, I'll upload a fix today :)

**Comment by therealspoljo** [comment]
It's on Bukkit now: http://dev.bukkit.org/bukkit-plugins/smelter/files/17-smelter-v2-2-1/
